model_list:
  - model_name: azure-gpt-4o
    litellm_params:
      model: azure/<your-azure-model-deployment>
      api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_key: os.environ/AZURE_API_KEY # runs os.getenv("AZURE_API_KEY")
      api_version: "2025-01-01-preview"
  - model_name: ollama-qwen3-4b
    litellm_params:
      model: ollama_chat/qwen3-Q4_K_M:4b
      api_base: os.environ/OLLAMA_API_BASE # runs os.getenv("OLLAMA_API_BASE")
      # api_key: os.environ/OLLAMA_API_KEY # runs os.getenv("OLLAMA_API_KEY")
      # api_version: "2025-12-24"
